### ISSUE TITLE
Configure Azure SSO for Argo CD

### ISSUE THREAD

**Issue by adamrushuk** [adamrushuk/devops-lab#171]
**Todo**

- [ ] Add missing `Sign on URL` in Ent App `Basic SAML Configuration` SSO config
- [ ] Add missing `email user.userprincipalname` claim in `User Attributes & Claims` SSO config
- [ ] Add missing SAML Signing Certificate in Ent App SSO config: https://docs.microsoft.com/en-us/graph/application-saml-sso-configure-api?tabs=http#step-4-configure-signing-certificate

- [x] https://argoproj.github.io/argo-cd/operator-manual/user-management/microsoft/
- [x] Fix RBAC using AAD Group ID - default rbac roles not required
- [ ] Investigate using Terraform for all AAD requirements
  - [x] Manually configure AAD Enterprise Application, then use `azuread_application` data source to view properties: https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/application
    - [x] Create a Service Principle to make an App Reg and Enterprise App: https://github.com/hashicorp/terraform-provider-azuread/issues/7#issuecomment-529597534
    - [x] UPDATE: Enterprise Apps are not supported atm, but possible workaround here: https://github.com/hashicorp/terraform-provider-azuread/issues/173#issuecomment-663727531
    - [x] workaround? https://github.com/hashicorp/terraform-provider-azuread/issues/164#issuecomment-685817218
  - [x] Enterprise Application Certificate (Base64) will need downloading, and base64 output
  - [ ] SSO URLs can be interpolated using `templatefile` function: https://www.terraform.io/docs/configuration/functions/templatefile.html
- [x] Use kubectl merge patch to update Argo CD ConfigMaps

**Comment by adamrushuk** [comment]
Leaving this as partially automated, and waiting for Terraform to support new Graph API.
Claims Mapping is a PITA for a one-off setting: https://docs.microsoft.com/en-us/graph/application-saml-sso-configure-api?tabs=http#step-3-configure-claims-mapping
